name: Test Fusion Library

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.3 ]
        laravel: [ 11.* ]
        dependency-version: [ prefer-lowest, prefer-stable ]

    name: "P:${{ matrix.php }}, L:${{ matrix.laravel }}, V: ${{ matrix.dependency-version }}"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Composer Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: composer-${{ matrix.laravel }}-${{ matrix.php }}-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install PHP Dependencies
        run: |
          composer self-update
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'packages/vue/package.json'

      - name: Install Node Dependencies
        run: npm install
        working-directory: packages/vue

      - name: Run npm tests
        run: npm run test
        working-directory: packages/vue

      - name: Run PHP Tests
        run: vendor/bin/phpunit